steps:
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args:
    - --destination=gcr.io/mads/content-filter-api
    - --cache=true
    - --context=src
    volumes:
    - name: "ssh"
      path: "/root/.ssh"
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'content-filter-api', '--image', 'gcr.io/mads/content-filter-api', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--service-account', 'p-hartford-sweat@datacose.iam.gserviceaccount.com']